// ghostRideFragments.js

// Generic ride fragments, all starting with "The ..."
const RIDE_FRAGMENTS = [
  "The opening scene",
  "The ending scene",
  "The first drop",
  "The big drop",
  "The small drops",
  "The launch",
  "The slow climb",
  "The backwards part",
  "The quiet moment",
  "The surprise twist",
  "The main storyline",
  "The side storyline",
  "The pre‑show",
  "The safety video",
  "The on‑ride music",
  "The background music",
  "The sound effects",
  "The lighting effects",
  "The fog effects",
  "The special effects",
  "The animatronics",
  "The main character",
  "The villain character",
  "The supporting cast",
  "The big reveal",
  "The fake ending",
  "The final turn",
  "The sharp turn",
  "The spinning part",
  "The bouncing section",
  "The water splash",
  "The tiny splash",
  "The giant splash",
  "The tunnel section",
  "The dark tunnel",
  "The bright tunnel",
  "The outdoor section",
  "The indoor section",
  "The rooftop view",
  "The park view",
  "The starry sky",
  "The fireworks scene",
  "The projection mapping",
  "The screen scene",
  "The practical sets",
  "The ride vehicles",
  "The lap bar",
  "The seat belts",
  "The loading area",
  "The unloading area",
  "The station lights",
  "The ride photo",
  "The on‑ride camera",
  "The first room",
  "The second room",
  "The final room",
  "The left side",
  "The right side",
  "The front row",
  "The back row",
  "The middle row",
  "The big loop",
  "The banked turn",
  "The slow floaty part",
  "The fast section",
  "The acceleration",
  "The sudden stop",
  "The drop sound",
  "The scream moment",
  "The countdown",
  "The safety spiel",
  "The hidden details",
  "The Easter eggs",
  "The smell effects",
  "The wind effects",
  "The water mist",
  "The lightning effect",
  "The earthquake scene",
  "The space scene",
  "The jungle scene",
  "The city scene",
  "The underwater scene",
  "The volcano scene",
  "The haunted scene",
  "The dinosaur scene",
  "The pirate scene",
  "The futuristic scene",
  "The castle scene",
  "The cave scene",
  "The bridge scene",
  "The elevator moment",
  "The drop sequence",
  "The lift hill",
  "The curve at the end",
  "The final joke",
  "The goodbye line",
  "The theming in line",
  "The music in line",
  "The props in line",
  "The exit hallway",
  "The gift shop"
];

// Simple helper to pick a random fragment
function getRandomRideFragment() {
  const idx = Math.floor(Math.random() * RIDE_FRAGMENTS.length);
  return RIDE_FRAGMENTS[idx];
}

// Expose globally for your existing inline scripts
window.RIDE_FRAGMENTS = RIDE_FRAGMENTS;
window.getRandomRideFragment = getRandomRideFragment;

// If you ever use modules, you can also export:
// export { RIDE_FRAGMENTS, getRandomRideFragment };
