// ghostRideFragments.js

// Generic ride fragments, all starting with "..."
const RIDE_FRAGMENTS = [
  "opening scene",
  "ending scene",
  "first drop",
  "big drop",
  "small drops",
  "launch",
  "slow climb",
  "backwards part",
  "quiet moment",
  "surprise twist",
  "main storyline",
  "side storyline",
  "pre‑show",
  "safety video",
  "on‑ride music",
  "background music",
  "sound effects",
  "lighting effects",
  "fog effects",
  "special effects",
  "animatronics",
  "main character",
  "villain character",
  "supporting cast",
  "big reveal",
  "fake ending",
  "final turn",
  "sharp turn",
  "spinning part",
  "bouncing section",
  "water splash",
  "tiny splash",
  "giant splash",
  "tunnel section",
  "dark tunnel",
  "bright tunnel",
  "outdoor section",
  "indoor section",
  "rooftop view",
  "park view",
  "starry sky",
  "fireworks scene",
  "projection mapping",
  "screen scene",
  "practical sets",
  "ride vehicles",
  "lap bar",
  "seat belts",
  "loading area",
  "unloading area",
  "station lights",
  "ride photo",
  "on‑ride camera",
  "first room",
  "second room",
  "final room",
  "left side",
  "right side",
  "front row",
  "back row",
  "middle row",
  "big loop",
  "banked turn",
  "slow floaty part",
  "fast section",
  "acceleration",
  "sudden stop",
  "drop sound",
  "scream moment",
  "countdown",
  "safety spiel",
  "hidden details",
  "Easter eggs",
  "smell effects",
  "wind effects",
  "water mist",
  "lightning effect",
  "earthquake scene",
  "space scene",
  "jungle scene",
  "city scene",
  "underwater scene",
  "volcano scene",
  "haunted scene",
  "dinosaur scene",
  "pirate scene",
  "futuristic scene",
  "castle scene",
  "cave scene",
  "bridge scene",
  "elevator moment",
  "drop sequence",
  "lift hill",
  "curve at end",
  "final joke",
  "goodbye line",
  "theming in line",
  "music in line",
  "props in line",
  "exit hallway",
  "gift shop"
];

// Simple helper to pick a random fragment
function getRandomRideFragment() {
  const idx = Math.floor(Math.random() * RIDE_FRAGMENTS.length);
  return RIDE_FRAGMENTS[idx];
}

// Expose globally for your existing inline scripts
window.RIDE_FRAGMENTS = RIDE_FRAGMENTS;
window.getRandomRideFragment = getRandomRideFragment;

// If you ever use modules, you can also export:
// export { RIDE_FRAGMENTS, getRandomRideFragment };
