// parks-data.js
window.PARKS = {
  attractions: [
    // Magic Kingdom – rides
    { name: 'Seven Dwarfs Mine Train', land: 'Fantasyland' },
    { name: 'Space Mountain', land: 'Tomorrowland' },
    { name: 'Peter Pan’s Flight', land: 'Fantasyland' },
    { name: 'TRON Lightcycle / Run', land: 'Tomorrowland' },
    { name: 'Tiana’s Bayou Adventure', land: 'Frontierland' },
    { name: 'Big Thunder Mountain Railroad', land: 'Frontierland' },
    { name: 'The Barnstormer', land: 'Storybook Circus' },
    { name: 'Tomorrowland Speedway', land: 'Tomorrowland' },
    { name: 'Buzz Lightyear’s Space Ranger Spin', land: 'Tomorrowland' },
    { name: 'Haunted Mansion', land: 'Liberty Square' },
    { name: 'Pirates of the Caribbean', land: 'Adventureland' },
    { name: 'Jungle Cruise', land: 'Adventureland' },
    { name: 'it’s a small world', land: 'Fantasyland' },
    { name: 'Dumbo the Flying Elephant', land: 'Storybook Circus' },
    { name: 'Under the Sea ~ Journey of the Little Mermaid', land: 'Fantasyland' },
    { name: 'Tomorrowland Transit Authority PeopleMover', land: 'Tomorrowland' },
    { name: 'Walt Disney’s Carousel of Progress', land: 'Tomorrowland' },
    { name: 'Mad Tea Party', land: 'Fantasyland' },
    { name: 'The Many Adventures of Winnie the Pooh', land: 'Fantasyland' },
    { name: 'Prince Charming Regal Carrousel', land: 'Fantasyland' },
    { name: 'Liberty Square Riverboat', land: 'Liberty Square' },
    { name: 'The Magic Carpets of Aladdin', land: 'Adventureland' },
    { name: 'Astro Orbiter', land: 'Tomorrowland' },

    // Magic Kingdom – shows/attractions
    { name: 'Mickey’s PhilharMagic', land: 'Fantasyland' },
    { name: 'Walt Disney’s Enchanted Tiki Room', land: 'Adventureland' },
    { name: 'Country Bear Jamboree', land: 'Frontierland' },
    { name: 'Hall of Presidents', land: 'Liberty Square' },
    { name: 'Monsters, Inc. Laugh Floor', land: 'Tomorrowland' },
    { name: 'Festival of Fantasy Parade', land: 'Park-wide' },
    { name: 'Mickey’s Magical Friendship Faire', land: 'Central Plaza' },
    { name: 'Meet Mickey at Town Square Theater', land: 'Main Street, U.S.A.' },
    { name: 'Princess Fairytale Hall', land: 'Fantasyland' },
    { name: 'Mirabel Meet and Greet (Fairytale Garden)', land: 'Fantasyland' },
    { name: 'Cinderella Castle Mural Walkthrough', land: 'Central Plaza' },
    { name: 'Swiss Family Treehouse', land: 'Adventureland' },
    { name: 'Tom Sawyer Island', land: 'Frontierland' },
    { name: 'The Dapper Dans', land: 'Main Street, U.S.A.' },
    { name: 'Happily Ever After', land: 'Park-wide' },
    { name: 'Disney Starlight: Dream the Night Away', land: 'Central Plaza' },

    // EPCOT – rides
    { name: 'Guardians of the Galaxy: Cosmic Rewind', land: 'World Discovery' },
    { name: 'Test Track', land: 'World Discovery' },
    { name: 'Mission: SPACE', land: 'World Discovery' },
    { name: 'Spaceship Earth', land: 'World Celebration' },
    { name: 'Soarin’ Around the World', land: 'World Nature' },
    { name: 'Living with the Land', land: 'World Nature' },
    { name: 'The Seas with Nemo & Friends', land: 'World Nature' },
    { name: 'Journey Into Imagination with Figment', land: 'World Celebration' },
    { name: 'Gran Fiesta Tour Starring The Three Caballeros', land: 'World Showcase – Mexico' },
    { name: 'Frozen Ever After', land: 'World Showcase – Norway' },
    { name: 'Remy’s Ratatouille Adventure', land: 'World Showcase – France' },

    // EPCOT – attractions
    { name: 'Turtle Talk with Crush', land: 'World Nature' },
    { name: 'SeaBase Aquarium', land: 'World Nature' },
    { name: 'Journey of Water, Inspired by Moana', land: 'World Nature' },
    { name: 'Disney & Pixar Short Film Festival', land: 'World Celebration' },
    { name: 'Awesome Planet', land: 'World Nature' },
    { name: 'Reflections of China', land: 'World Showcase – China' },
    { name: 'Impressions de France', land: 'World Showcase – France' },
    { name: 'Beauty and the Beast Sing-Along', land: 'World Showcase – France' },
    { name: 'Canada Far and Wide', land: 'World Showcase – Canada' },
    { name: 'The American Adventure', land: 'World Showcase – The American Adventure' },
    { name: 'ImageWorks – The “What If” Labs', land: 'World Celebration' },
    { name: 'Project Tomorrow: Inventing the Wonders of the Future', land: 'World Celebration' },
    { name: 'Mission: SPACE Advanced Training Lab', land: 'World Discovery' },

    // Hollywood Studios – rides
    { name: 'Star Wars: Rise of the Resistance', land: 'Star Wars: Galaxy’s Edge' },
    { name: 'Millennium Falcon: Smugglers Run', land: 'Star Wars: Galaxy’s Edge' },
    { name: 'Slinky Dog Dash', land: 'Toy Story Land' },
    { name: 'Toy Story Mania!', land: 'Toy Story Land' },
    { name: 'Alien Swirling Saucers', land: 'Toy Story Land' },
    { name: 'Mickey & Minnie’s Runaway Railway', land: 'Hollywood Boulevard' },
    { name: 'The Twilight Zone Tower of Terror', land: 'Sunset Boulevard' },
    { name: 'Rock \'n\' Roller Coaster Starring Aerosmith', land: 'Sunset Boulevard' },

    // Hollywood Studios – attractions/shows
    { name: 'Fantasmic!', land: 'Sunset Boulevard' },
    { name: 'Beauty and the Beast – Live on Stage', land: 'Sunset Boulevard' },
    { name: 'Indiana Jones Epic Stunt Spectacular!', land: 'Echo Lake' },
    { name: 'For the First Time in Forever: A Frozen Sing-Along Celebration', land: 'Echo Lake' },
    { name: 'Disney Junior Play & Dance!', land: 'Animation Courtyard' },
    { name: 'Disney Villains: Unfairly Ever After', land: 'Sunset Boulevard' },
    { name: 'Vacation Fun – An Original Animated Short with Mickey & Minnie', land: 'Echo Lake' },
    { name: 'The Little Mermaid – A Musical Adventure', land: 'Animation Courtyard' },
    { name: 'Walt Disney Presents', land: 'Animation Courtyard' },
    { name: 'Mickey & Minnie at Red Carpet Dreams', land: 'Commissary Lane' },
    { name: 'Olaf at Celebrity Spotlight', land: 'Echo Lake' },
    { name: 'Disney Junior Stars Meet and Greets', land: 'Animation Courtyard' },
    { name: 'Star Wars Launch Bay', land: 'Animation Courtyard' },
    { name: 'Sulley Meet and Greet', land: 'Animation Courtyard' },
    { name: 'Edna Mode Experience', land: 'Pixar Place' },
    { name: 'Toy Story Character Meet and Greets', land: 'Toy Story Land' },
    { name: 'The Mandalorian and Grogu (Roaming)', land: 'Star Wars: Galaxy’s Edge' },
    { name: 'Stormtroopers and Kylo Ren (Roaming)', land: 'Star Wars: Galaxy’s Edge' },

    // Animal Kingdom – rides
    { name: 'Avatar Flight of Passage', land: 'Pandora – The World of Avatar' },
    { name: 'Na’vi River Journey', land: 'Pandora – The World of Avatar' },
    { name: 'Expedition Everest – Legend of the Forbidden Mountain', land: 'Asia' },
    { name: 'Kali River Rapids', land: 'Asia' },
    { name: 'DINOSAUR', land: 'DinoLand U.S.A.' },
    { name: 'Kilimanjaro Safaris', land: 'Africa' },

    // Animal Kingdom – attractions/shows
    { name: 'Festival of the Lion King', land: 'Africa' },
    { name: 'Finding Nemo: The Big Blue… and Beyond!', land: 'DinoLand U.S.A.' },
    { name: 'Feathered Friends in Flight!', land: 'Asia' },
    { name: 'Maharajah Jungle Trek', land: 'Asia' },
    { name: 'Gorilla Falls Exploration Trail', land: 'Africa' },
    { name: 'Discovery Island Trails', land: 'Discovery Island' },
    { name: 'The Oasis Exhibits', land: 'The Oasis' },
    { name: 'Tree of Life Awakenings', land: 'Discovery Island' },
    { name: 'The Boneyard', land: 'DinoLand U.S.A.' },
    { name: 'Wildlife Express Train', land: 'Africa' },
    { name: 'Animation Experience at Conservation Station', land: 'Rafiki’s Planet Watch' },
    { name: 'Kevin (Roaming)', land: 'Discovery Island' }
  ]
};
