window.DISNEY_LINE_QUESTIONS = [
  "Which character should not be here at all?",
  "Which character deserves way more time?",
  "Which character would you spin off into their own ride?",
  "Which line you would cut?",
  "Which line you quote the most?",
  "Which line makes you laugh every time?",
  "Which moment feels like peak Disney?",
  "Which part of the queue is the best?",
  "Which part of the queue is pointless?",
  "Which queue detail you always look for?",
  "Which part of the queue ruins the immersion?",
  "Which part of the queue sells the story?",
  "Which preshow moment do you love most?",
  "Which preshow line do you remember most?",
  "Which effect blows you away?",
  "Which effect looks the fakest?",
  "Which animatronic is your favorite?",
  "Which animatronic disappoints you?",
  "Which animatronic movement looks weirdest?",
  "Which animatronic feels the most alive?",
  "Which animatronic would you remove?",
  "Which animatronic would you add?",
  "Which animatronic you'd build a whole scene around?",
  "Which bit of tech feels like a cheap shortcut?",
  "Which bit of tech feels like magic?",
  "Which scene drags the most?",
  "Which scene goes by too fast?",
  "Which pacing choice feels wrong?",
  "Which pacing choice feels perfect?",
  "Which musical moment is elite?",
  "Which melody sticks in your head after you ride?",
  "Which sound effect stands out most?",
  "Which voice performance is the best?",
  "Which effect you wish they would improve?",
  "Which effect you wish they would remove?",
  "Which broken effect or scene do you wish they would fix?",
  "What hidden mickeys are your favorite on this attraction?",
  "Which describe this attraction's smell in three words or less?",
  "What is the coolest setpiece?",
  "What is the least cool setpiece?",
  "Which scene has the coolest lighting?",
  "Which scene has the worst lighting?",
  "Which part feels the most immersive?",
  "Which part completely breaks the immersion?",
  "Which change would make most fans furious?",
  "Which classic element they should never touch?",
  "Which classic element should be removed?",
  "Which modern update would most improve the attraction?",
  "Which old-school update would most improve the attraction?",
  "What is your hottest take on this attraction?",
  "Which moment is the most overrated?",
  "Which moment is the most underrated?",
  "Which moment makes you want to re-ride?",
  "How would you change the beginning?",
  "How would you change the end?",
  "How would you change the pre-show?",
  "How would you change the post-show?",
  "Which new scene would you add?",
  "Which scene would you improve?",
  "Which character would you add?",
  "Which character would you remove?",
  "Which scene from this attraction would you love to see from backstage?",
  "Which part of this attraction would you most like to redesign?",
  "Which part of this attraction do fans overhype the most?",
  "Which part of this attraction can only true fans appreciate?",
  "Which scene would you cut?",
  "Which scene would you expand?",
  "Describe this attraction in three words or less",
  "Which scene would you expand into its own mini-ride?"
];
