// questions.js
window.DISNEY_LINE_QUESTIONS = [
"Which scene is the most overrated?",
"Which scene is the most underrated?",
"Which character is the worst?",
"Which character secretly carries this attraction?",
"Which character should not be here at all?",
"Which character deserves way more time?",
"Which character is the most forgettable?",
"Which character has the best entrance?",
"Which character has the weakest design?",
"Which character would you spin off into their own ride?",
"Which line is the best in the whole attraction?",
"Which line is the cringiest?",
"Which line you would cut instantly?",
"Which line you quote the most?",
"Which line makes you laugh every time?",
"Which line breaks the mood?",
"Which joke never lands for you?",
"Which joke always lands for you?",
"Which joke feels the most forced?",
"Which joke is the most clever?",
"Which story moment hits the hardest?",
"Which story moment completely fails?",
"Which story beat confuses you the most?",
"Which story beat you wish they leaned into more?",
"Which part of the story feels missing?",
"Which twist or reveal works best?",
"Which twist or reveal falls flat?",
"Which scene feels like pure filler?",
"Which moment feels like peak Disney?",
"Which moment makes you go, ‘That’s it?’",
"Which moment feels like the true finale?",
"Which transition between scenes works best?",
"Which transition between scenes feels rough?",
"Which part of the queue is the best?",
"Which part of the queue is pointless?",
"Which queue detail you always look for?",
"Which queue detail you wish more people noticed?",
"Which part of the queue ruins the immersion?",
"Which part of the queue sells the story?",
"Which preshow moment you love most?",
"Which preshow moment you would delete?",
"Which preshow line you remember most?",
"Which preshow gag works best?",
"Which preshow element feels like a waste?",
"Which preshow element gets you hyped?",
"Which visual effect blows you away?",
"Which visual effect looks the fakest?",
"Which effect used to impress you but doesn’t now?",
"Which effect still blows your mind?",
"Which effect feels the most outdated?",
"Which effect feels way ahead of its time?",
"Which animatronic is the MVP?",
"Which animatronic disappoints you?",
"Which animatronic movement looks weirdest?",
"Which animatronic feels the most alive?",
"Which animatronic you’d remove first?",
"Which animatronic you’d build a whole scene around?",
"Which technical element feels most broken?",
"Which technical element you hardly notice?",
"Which technical flourish makes you smile?",
"Which bit of tech feels like a cheap shortcut?",
"Which bit of tech feels like magic?",
"Which moment drags the most?",
"Which moment goes by too fast?",
"Which part you would shorten first?",
"Which part you would stretch out longer?",
"Which pacing choice feels wrong?",
"Which pacing choice feels perfect?",
"Which musical moment is elite?",
"Which musical moment is the weakest?",
"Which melody sticks in your head after you ride?",
"Which musical cue hits at the perfect time?",
"Which use of silence is most effective?",
"Which use of music kills the mood?",
"Which sound effect stands out most?",
"Which sound effect annoys you?",
"Which ambient sound pulls you into the world?",
"Which voice performance is the best?",
"Which voice performance is the weakest?",
"Which tiny detail you obsess over?",
"Which tiny detail you wish they would fix?",
"Which prop or set piece you always notice?",
"Which Easter egg you love most?",
"Which Easter egg feels out of place?",
"Which background detail feels like the smartest choice?",
"Which smell (or lack of smell) stands out most?",
"Which lighting moment is the coolest?",
"Which lighting choice ruins the illusion?",
"Which color palette or look defines this attraction for you?",
"Which part feels the most immersive?",
"Which part completely breaks the immersion?",
"Which change would make fans furious?",
"Which change would make this 10x better?",
"Which bold change you actually want Disney to make?",
"Which classic element they should never touch?",
"Which piece of nostalgia is doing all the heavy lifting?",
"Which modern update improved the attraction most?",
"Which opinion you have about this attraction would start an argument?",
"Which hill you would die on about this attraction?",
"Which moment proves this ride is overrated?",
"Which moment proves this ride is underrated?",
"Which part screams ‘old and tired’?",
"Which part feels shockingly modern?",
"Which scene would you show a first-timer to explain this ride?",
"Which moment makes you want to ride again?",
"Which moment makes you think once is enough?",
"Which single change to the ending would improve it most?",
"Which new scene would you add if you had unlimited budget?",
"Which crossover character you’d drop into this attraction?",
"Which meme or joke about this ride you secretly agree with?",
"Which moment you’d love to see from backstage?",
"Which part you’d most like to redesign yourself?"
];
