window.DISNEY_LINE_QUESTIONS = [
"Which scene is the most overrated?",
"Which scene is the most underrated?",
"Which character is the worst?",
"Which character secretly carries this attraction?",
"Which character should not be here at all?",
"Which character deserves way more time?",
"Which character is the most forgettable?",
"Which character has the best entrance?",
"Which character has the weakest design?",
"Which character would you spin off into their own ride?",
"Which line is the best in the whole attraction?",
"Which line is the cringiest?",
"Which line you would cut instantly?",
"Which line you quote the most?",
"Which line makes you laugh every time?",
"Which line breaks the mood?",
"Which joke never lands for you?",
"Which joke always lands for you?",
"Which joke feels the most forced?",
"Which joke is the most clever?",
"Which moment feels like peak Disney?",
"Which moment makes you go, 'That's it?'",
"Which part of the queue is the best?",
"Which part of the queue is pointless?",
"Which queue detail you always look for?",
"Which queue detail you wish more people noticed?",
"Which part of the queue ruins the immersion?",
"Which part of the queue sells the story?",
"Which preshow moment you love most?",
"Which preshow moment you would delete?",
"Which preshow line you remember most?",
"Which preshow gag works best?",
"Which preshow element gets you hyped?",
"Which visual effect blows you away?",
"Which visual effect looks the fakest?",
"Which effect still blows your mind?",
"Which effect feels the most outdated?",
"Which effect feels way ahead of its time?",
"Which animatronic is the MVP?",
"Which animatronic disappoints you?",
"Which animatronic movement looks weirdest?",
"Which animatronic feels the most alive?",
"Which animatronic you’d remove first?",
"Which animatronic you’d build a whole scene around?",
"Which technical element feels most broken?",
"Which technical flourish makes you smile?",
"Which bit of tech feels like a cheap shortcut?",
"Which bit of tech feels like magic?",
"Which moment drags the most?",
"Which moment goes by too fast?",
"Which part you would shorten first?",
"Which part you would stretch out longer?",
"Which pacing choice feels wrong?",
"Which pacing choice feels perfect?",
"Which musical moment is elite?",
"Which melody sticks in your head after you ride?",
"Which musical cue hits at the perfect time?",
"Which use of silence is most effective?",
"Which use of music kills the mood?",
"Which sound effect stands out most?",
"Which sound effect annoys you?",
"Which voice performance is the best?",
"Which voice performance is the weakest?",
"Which tiny detail you wish they would fix?",
"Which prop or set piece you always notice?",
"Which Easter egg you love most?",
"Which Easter egg feels out of place?",
"Which smell (or lack of smell) stands out most?",
"Which lighting moment is the coolest?",
"Which lighting choice ruins the illusion?",
"Which part feels the most immersive?",
"Which part completely breaks the immersion?",
"Which change would make fans furious?",
"Which change would make this 10x better?",
"Which bold change you actually want Disney to make?",
"Which classic element they should never touch?",
"Which piece of nostalgia is doing all the heavy lifting?",
"Which modern update improved the attraction most?",
"Which opinion you have about this attraction would start an argument?",
"Which hill you would die on about this attraction?",
"Which moment proves this ride is overrated?",
"Which moment proves this ride is underrated?",
"Which part screams 'old and tired'?",
"Which part feels shockingly modern?",
"Which scene would you show a first-timer to explain this ride?",
"Which moment makes you want to ride again?",
"Which moment makes you think once is enough?",
"Which single change to the ending would improve it most?",
"Which new scene would you add if you had unlimited budget?",
"Which crossover character you’d drop into this attraction?",
"Which meme or joke about this ride you secretly agree with?",
"Which moment you’d love to see from backstage?",
"Which part you’d most like to redesign yourself?",
"Which part of this ride fans overhype the most?",
"Which part of this ride only true fans appreciate?",
"Which scene would you cut to make this ride tighter?",
"Which scene would you expand into its own mini-ride?",
"Which moment makes you think, 'Disney would never build this today'?",
"Which part of this ride feels the most like a movie scene?",
"Which part of this ride feels the most like a stage show?",
"Which moment is way funnier than the designers probably intended?",
"Which moment is way scarier than the designers probably intended?",
"Which rule or safety spiel line you secretly ignore in your head?",
"Which moment makes you wish phones were banned on this ride?",
"Which part of the ride you always point out to first-timers?"
];
